ci: fix pr

diff --git a/.github/workflows/update-flake.yaml b/.github/workflows/update-flake.yaml
--- a/.github/workflows/update-flake.yaml
+++ b/.github/workflows/update-flake.yaml
@@ -66,6 +66,7 @@ jobs:
           rm pr_body.md
 
       - uses: EndBug/add-and-commit@v10 # You can change this to use a specific version.
+        id: commit
         with:
           author_name: crystals forgojo actions runner
           author_email: runner@git.iw2tryhard.dev
@@ -75,20 +76,62 @@ jobs:
             ${{ steps.pr_body.outputs.content }}
           new_branch: update-flake-lock 
 
-      - name: Install tea
-        run: nix profile install nixpkgs#tea
-
+      # - name: Create Pull Request
+      #   id: create-pull-request
+      #   uses: https://git.theless.one/actions/create-pr@main
+      #   with:
+      #     source-branch: update-flake-lock
+      #     token: ${{ secrets.FJ_TOKEN }}
+      #     user: itscrystalline
+      #     auto-merge: true
+      #     delete-branch: true
       - name: Create Pull Request
-        id: create-pull-request
-        uses: https://git.theless.one/actions/create-pr@main
-        with:
-          source-branch: update-flake-lock
-          title: 'chore: Update flake (automated)'
-          description: ${{ steps.pr_body.outputs.content }}
-          token: ${{ secrets.FJ_TOKEN }}
-          user: itscrystalline
-          auto-merge: true
-          delete-branch: true
+        id: create-pr
+        if: steps.commit.outputs.committed == 'true'
+        env:
+          USER: itscrystalline
+          TOKEN: ${{ secrets.FJ_TOKEN }}
+          FORGEJO_SERVER_URL: ${{ forgejo.server_url }}
+          TITLE: 'chore: Update flake (automated)'
+          DESCRIPTION: ${{ steps.pr_body.outputs.content }}
+          REPO: ${{ forgejo.repository }}
+        run: |
+          nix profile install nixpkgs#tea
+
+          tea login add --name "$USER" --token "$TOKEN" --url "$FORGEJO_SERVER_URL"
+
+          tea pr create \
+            --login "$USER" \
+            --title "$TITLE" \
+            --description "$DESCRIPTION" \
+            --repo "$REPO" | tail | grep -oP '/\K\d+' > pr
+
+          echo -n "pr=$(cat pr)" >> $FORGEJO_OUTPUT
+
+      - name: Enable automatic merge
+        if: steps.create-pr.outputs.pr > 0
+        id: auto-merge
+        env:
+          TOKEN: ${{ inputs.token }}
+          FORGEJO_SERVER_URL: ${{ inputs.server }}
+          REPO: ${{ inputs.repo }}
+          PR_NUMBER: ${{ steps.create-pr.outputs.pr }}
+          PAYLOAD: |
+            {
+              "Do": "merge",
+              "delete_branch_after_merge": ${{ inputs.delete-branch == 'true' }},
+              "merge_when_checks_succeed": true,
+              "force_merge": false
+            }
+        run: |
+          type -P curl > /dev/null \
+            || { echo "Dependency missing in PATH: curl"; exit 1; }
+
+          curl --fail -s -X POST \
+            -H "Authorization: token $TOKEN" \
+            -H "Content-Type: application/json" \
+            -d "$PAYLOAD" \
+            "$FORGEJO_SERVER_URL/api/v1/repos/$REPO/pulls/$PR_NUMBER/merge"
 
       - name: PR number
-        run: echo 'PR ${{ steps.create-pull-request.outputs.pr }}'
+        run: echo 'PR ${{ steps.create-pr.outputs.pr }}'
